# Generated by Django 3.2.3 on 2021-05-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_follow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Рецепты-Ингредиенты', 'verbose_name_plural': 'Рецепты-Ингредиенты'},
        ),
    ]
