# Generated by Django 3.2.3 on 2021-05-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='measurment',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(default='null', max_length=30, verbose_name='Единицы измерений'),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
