# Generated by Django 3.2.3 on 2021-05-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_ingredient_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement',
        ),
    ]
