# Generated by Django 3.2.3 on 2021-05-31 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_ingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.measurement', verbose_name='Название ингредиента'),
        ),
    ]
