# Generated by Django 3.2.3 on 2021-05-31 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_ingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(max_length=100, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipe.measurement', verbose_name='Единицы измерений'),
        ),
    ]
