# Generated by Django 3.2.3 on 2021-06-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0023_auto_20210613_1232'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
    ]
