# Generated by Django 3.2.3 on 2021-06-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0025_follow_unique_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Цвет'),
        ),
    ]
